tui_gradient_block::gen_example_code!(
    [
        MIDNIGHT_BLURPLE.base1.clone(),
        MIDNIGHT_BLURPLE.double_right.clone(),
        MIDNIGHT_BLURPLE.base2.clone(),
    ],
    [
        MIDNIGHT_BLURPLE_TITLES.base1.clone(),
        MIDNIGHT_BLURPLE_TITLES.double_right.clone(),
        MIDNIGHT_BLURPLE_TITLES.base2.clone(),
    ]
);
