tui_gradient_block::gen_example_code!(
    [
        MISTY_BLUE.double_right.clone(),
        MISTY_BLUE.base1.clone(),
        MISTY_BLUE.base2.clone(),
    ],
    [
        MISTY_BLUE_TITLES.double_right.clone(),
        MISTY_BLUE_TITLES.base1.clone(),
        MISTY_BLUE_TITLES.base2.clone(),
    ]
);
