tui_gradient_block::gen_example_code!(
    [
        RUSTY_RUINS.double_right.clone(),
        RUSTY_RUINS.double_vertical.clone(),
        RUSTY_RUINS.base1.clone(),
    ],
    [
        RUSTY_RUINS_TITLES.double_right.clone(),
        RUSTY_RUINS_TITLES.double_vertical.clone(),
        RUSTY_RUINS_TITLES.base1.clone(),
    ]
);
